name: flutter_link_nav
description: "Combining Navigator with Deep Links (Android) and Universal Links (iOS) in Flutter"
homepage: https://github.com/ngominhtrungit
repository: https://github.com/ngominhtrungit/flutter_link_nav
issue_tracker: https://github.com/ngominhtrungit/flutter_link_nav/issues
topics: [deeplink, navigator, universal-links]

version: 2.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_link_nav
    iosBundleIdentifier: com.example.flutterLinkNav

platforms:
  android:
  ios:
  macos:

screenshots:
  - description: The flutter link nav package logo.
    path: assets/logo.png