name: flutter_link_nav
description: "Combining Navigator with Deep Links (Android) and Universal Links (iOS) in Flutter"
homepage: https://github.com/ngominhtrungit
issue_tracker: https://github.com/ngominhtrungit/flutter_link_nav/issues

version: 1.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.flutter_link_nav
    iosBundleIdentifier: com.example.flutterLinkNav
